name: Update README

on:
  schedule:
    - cron: '0 0 * * *' # Ежедневно в 00:00 UTC
  workflow_dispatch:

jobs:
  youtube:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Get latest YouTube videos (RSSHub)
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://rsshub.app/youtube/user/deworld_ru"
          max_post_count: 5
          readme_path: README.md
          comment_tag_name: "YOUTUBE"
          template: "- [$title]($url) • $date"
          date_format: "dd.MM.yyyy"
          gh_token: ${{ secrets.GITHUB_TOKEN }}
